### ISSUE TITLE
Warning about missing `self` links

### ISSUE THREAD

**Issue by gadomski** [stac-utils/stac-check#76]
While the spec says `self` links are strongly recommended (e.g. from the [item-spec](https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md#item-fields)),

![Screen Shot 2022-03-03 at 5 21 26 AM](https://user-images.githubusercontent.com/58314/156563774-2b4344ff-381e-4965-9043-fd19aef7bd1d.png)
 
the [best practices](https://github.com/radiantearth/stac-spec/blob/master/best-practices.md#relative-published-catalog) have multiple locations where a `self` link is _not_ recommended for all objects in a tree. E.g. in `Self-contained`:

> Only relative href's in structural `links` ... This also implies no `self` link, as that link must be absolute.

And `Relative published`:

> This is designed so that a self-contained catalog (of either type, with its assets or just metadata) can be 'published' online by just adding one field (the `self` link) to its root (Catalog or Collection).

IMO currently warning _every time_ a `self` link is missing is a false positive, and the warning should either be dropped or put-behind an opt-in flag. I also think this could/should also be opened an issue in `stac-spec` itself.

**Comment by jonhealy1** [comment]
Maybe a WARNING isn't always necessary for something that may just be a 'recommendation' too?

**Comment by jonhealy1** [comment]
@philvarner Do you think I should remove this check entirely? Making it conditional on different types of collections is an option maybe, but I don't know if it's achievable? What do you think?

**Comment by philvarner** [comment]
in stac-api-validator, I feel like there are some things that are currently warnings that are more like "are you sure you meant to do this?" -- for example, when datetime values that are not RFC 3339-compliant are accepted. 

I wouldn't remove it entirely.

I think you can probably come up with a good heuristic. 

The other option is having the ability to turn off specific checks link most linters do, so an implementer who intentionally didn't have self links could explicitly turn that warning off.
