### ISSUE TITLE
Relax pin on stac-validator?

### ISSUE THREAD

**Issue by TomAugspurger** [stac-utils/stac-check#88]
In https://github.com/stac-utils/stac-check/blob/71e7f1d167fe780923ef2a934f16b99598da6d70/setup.py#L22, this is pinned directly to stac-validator==3.2.0. This makes it hard to use stac-check in environments that want / need a different version of stac-validator.

Does that need to be pinned tightly, or can that be left to the user?

**Comment by jonhealy1** [comment]
Hi @TomAugspurger. Does `stac-validator>=3.1.0` work? Theoretically I know what you are saying but I am not sure why anyone would want to use older versions of stac-validator?

**Comment by jonhealy1** [comment]
https://github.com/stac-utils/stac-check/commit/d5d0232f9a19f4365b7c8b63ee4a1c2292097013

**Comment by TomAugspurger** [comment]
Thanks @jonhealy1! Generally speaking, the best practice is to pin to the lowest version of your dependency known to work with your package, as long as the additional maintenance cost isn't too high. `>=3.1.0` should work just fine.
