### ISSUE TITLE
Update README : section "Lint Dictionary"

### ISSUE THREAD

**Issue by Lunyxis** [stac-utils/stac-check#98]
Hi, 
 
Some update are needed in the README :) 

The import is from 'stac_check' and not 'stac_linter', and the input should be a path.

Suggestion below : 

```
from stac_check.lint import Linter

linter = Linter('<json_path>')

for k, v in linter.create_best_practices_dict().items():
    print(k, ":", v)
```

**Comment by jonhealy1** [comment]
@Lunyxis Hi. Thanks for the feedback. Would you like to make a pr with this update?

**Comment by Lunyxis** [comment]
Hi, PR #99 

Thk for the lib, it does a great job ! :)

**Comment by jonhealy1** [comment]
Thanks!
